CREATE DATABASE okosrecetkonyv;
USE okosrecetkonyv;
go

CREATE TABLE KEP (
	ID INT PRIMARY KEY IDENTITY(1,1)not null,
	Kep VARCHAR(max)
)


CREATE TABLE RECEPT (
	ID INT PRIMARY KEY IDENTITY(1,1) not null,
	Kep_ID INT not null,
	Nev VARCHAR(100),
	Leiras VARCHAR(max)
)

CREATE TABLE RECEPT_HOZZAVALO (
	Recept_ID INT not null,
	Hozzavalok_ID INT not null,
	Mertekegyseg_ID INT not null,
	Mennyiseg INT
)

CREATE TABLE HOZZAVALOK (
	ID INT PRIMARY KEY  IDENTITY(1,1) not null,
	Nev VARCHAR(50)
)


CREATE TABLE MERTEKEGYSEG (
	ID INT PRIMARY KEY IDENTITY(1,1) not null,
	Nev VARCHAR(10)
)

CREATE TABLE RECEPT_KATEGORIA (
	Recept_ID INT not null,
	Kategoria_ID INT not null
)

DROP TABLE IF EXISTS KATEGORIA;

CREATE TABLE KATEGORIA (
	ID INT PRIMARY KEY IDENTITY(1,1) not null,
	Kategorianev VARCHAR(50) not null
)

CREATE TABLE FELHASZNALO (
	ID INT PRIMARY KEY IDENTITY(1,1) not null,
	Nev VARCHAR(50) not null,
	Jelszo VARCHAR(1000) not null,
	Aktiv int
)

CREATE TABLE ERTEKELES (
	Recept_ID INT not null,
	Felhasznalo_ID INT not null,
	Ertekeles FLOAT
)

ALTER TABLE RECEPT
ADD CONSTRAINT FK_Kep_ID FOREIGN KEY (Kep_ID) REFERENCES Kep(ID)

ALTER TABLE RECEPT_HOZZAVALO
ADD CONSTRAINT FK_Recept_ID FOREIGN KEY (Recept_ID) REFERENCES Recept(ID)

ALTER TABLE RECEPT_HOZZAVALO
ADD CONSTRAINT FK_Hozzavalok_ID FOREIGN KEY (Hozzavalok_ID) REFERENCES HOZZAVALOK(ID)

ALTER TABLE RECEPT_HOZZAVALO
ADD CONSTRAINT FK_Mertekegyseg_ID FOREIGN KEY (Mertekegyseg_ID) REFERENCES Mertekegyseg(ID)

ALTER TABLE RECEPT_KATEGORIA
ADD CONSTRAINT FK1_Recept_ID FOREIGN KEY (Recept_ID) REFERENCES RECEPT(ID)

ALTER TABLE RECEPT_KATEGORIA
ADD CONSTRAINT FK_Kategoria_ID FOREIGN KEY (Kategoria_ID) REFERENCES KATEGORIA(ID)

ALTER TABLE ERTEKELES
ADD CONSTRAINT FK2_Recept_ID FOREIGN KEY (Recept_ID) REFERENCES RECEPT(ID)

ALTER TABLE ERTEKELES
ADD CONSTRAINT FK_Felhasznalo_ID FOREIGN KEY (Felhasznalo_ID) REFERENCES FELHASZNALO(ID);